alpha = 42
beta = 17
gamma = 3.14
delta = (alpha - beta) * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu / 16
delta = mu * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu / 16
delta = mu * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 2
xi = int(nu)
delta = xi * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 16
delta = mu * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu / 16
delta = nu * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 2
xi = int(nu)
delta = xi * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 16
delta = nu * 2
epsilon = delta / 4 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 3
xi = int(nu)
delta = xi * 2
epsilon = delta / 8 + 5.5
zeta = (epsilon ** 2) - (gamma * 10)
eta = zeta % beta
lamda = (eta * 3) + 7
mu = (lamda - 10) ** 2
nu = mu + 16
print(xi - 3)